export const RESOURCE = {
  PRODUCTION: "production",
  DEVELOPMENT: "development",
  INTERNAL_SERVER_ERROR: "Internal server error",
  CLOUDINARY_FOLDER: "projectImages",
  API: "api",
  V1: "/v1",
  ID: "id",
  POSITION: "position",
  ROLES: "/roles",
  CUSTOMERS: "/customers",
  MERCHANTS: "/merchants",
  AUTH: "/auth",
  CATEGORIES: "/categories",
  PRODUCTS: "/products",
  INVENTORIES: "/inventories",
  DISCOUNTS: "/discounts",
  TRANSACTIONS: "/transactions",
  COMMENTS: "/comments",
  REFUNDS: "/refunds",
};
